# tools/dawnpy/tox.ini
#
# SPDX-License-Identifier: Apache-2.0
#

[tox]
requires =
    tox>=4
env_list = format, flake8, type, py

[testenv]
description = run tests with coverage report
usedevelop=True
deps =
    pytest
    pytest-mock
    pytest-sugar
    coverage>=6
commands =
    coverage run -m pytest {posargs}
    coverage report --fail-under 100

[testenv:test]
description = run tests without coverage report (but in parallel)
usedevelop=True
deps =
    pytest
    pytest-mock
    pytest-sugar
    pytest-xdist
commands =
    pytest -n 4 {posargs}

[testenv:format]
description = run code formatter
skip_install = true
deps =
    isort
    black
commands =
    isort {posargs:src/dawnpy tests}
    black {posargs:src/dawnpy tests}

[testenv:flake8]
description = run flake8
skip_install = true
deps =
    flake8
    flake8-bugbear
    flake8-builtins
    flake8-walrus
    flake8-docstrings>=1.3.1
    pep8-naming
commands =
    flake8 --jobs 1 {posargs:src/dawnpy tests}

[testenv:type]
description = run type checks
deps =
    mypy
    types-PyYAML
commands =
    mypy --strict --pretty {posargs:src/dawnpy}

[pytest]
testpaths = tests
pythonpath = .
norecursedirs = .git .* *.egg* dist build
addopts = -rw
filterwarnings = error

[coverage:report]
precision = 2
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
    if TYPE_CHECKING:
    @abstractmethod
    except ImportError:

[flake8]
per-file-ignores =
    tests/*: D
max-complexity = 10
ignore =
    E203 W503
